on:
  push:
    branches:
      - release
    tags:
      - "v*"

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # trusted publishing + attestations
      actions: write # caching
      contents: write # see https://github.com/softprops/action-gh-release#permissions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Install Nix
        uses: cachix/install-nix-action@51f3067b56fe8ae331890c77d4e454f6d60615ff # v31.10.2
      - name: Build static-linked binary with musl
        run: nix build .#musl -Lv
      - name: Create tar
        run: tar -cvzf mirror-clone.tar.gz -C result/bin mirror-clone
      - name: Create GitHub release
        uses: softprops/action-gh-release@153bb8e04406b158c6c84fc1615b65b24149a1fe # v2.6.1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: true
          files: mirror-clone.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
