on:
  push:
    branches:
      - release
    tags:
      - "v*"

name: Release

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      id-token: write # trusted publishing + attestations
      actions: write # caching
      contents: write # see https://github.com/softprops/action-gh-release#permissions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - name: Build static-linked binary with musl
        run: nix build .#musl -Lv
      - name: Create tar
        run: tar -cvzf mirror-clone.tar.gz -C result/bin mirror-clone
      - name: Create GitHub release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: true
          files: mirror-clone.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
